services:
  web:
    container_name: trains.localhost
    build:
      context: .
      dockerfile: Dockerfile
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.trains.rule=Host(`trains.localhost`)"
        - "traefik.http.services.trains.loadbalancer.server.port=8080"
    networks:
      - traefik
      
networks:
  traefik:
    external: true
    name: traefik_default
    